# encoding: UTF-8
import unittest

from base import BaseTestCase
import json


class TestTaskBlueprint(BaseTestCase):
    """
    Tests the REST api for Task generated by flask-restfull.
    """

    def test_task_get(self):
        # Ensure login behaves correctly with correct credentials.
        with self.client:
            response = self.client.get(
                '/task',
            )
            self.assertEqual(response.status_code, 200)
            self.assertEqual(
                response.json,
                {
                    "num_results": 0,
                    "objects": [],
                    "page": 1,
                    "total_pages": 0,
                }
            )

    def test_task_post(self):

        with self.client:
            response = self.client.post(
                '/task',
                data='{"task": "Tomar um café", "done": false}',
                headers={
                    "Content-Type": "application/json"
                },
            )
            self.assertEqual(response.status_code, 201)
            self.assertEqual(
                response.json,
                {
                    "task": "Tomar um café",
                    "id": 1,
                    "done": False,
                }
            )

            response = self.client.get(
                '/task',
            )
            self.assertEqual(response.status_code, 200)
            self.assertEqual(
                response.json,
                {
                    "num_results": 1,
                    "objects": [
                        {
                            "id" : 1,
                            "task" : "Tomar um café",
                            "done" : False,
                        }
                    ],
                    "page": 1,
                    "total_pages": 1,
                }
            )


if __name__ == '__main__':
    unittest.main()
