"""empty message

Revision ID: 2cb92744e4b
Revises: None
Create Date: 2015-11-03 15:59:29.460892

"""

# revision identifiers, used by Alembic.
revision = '2cb92744e4b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
